Feat: Change to using ubuntu:25.04 as base
Co-authored-by: Martin Rippin <74295098+marrip@users.noreply.github.com>

diff --git a/containers/minimal/Dockerfile b/containers/minimal/Dockerfile
--- a/containers/minimal/Dockerfile
+++ b/containers/minimal/Dockerfile
@@ -1,17 +1,42 @@
-# Minimal contains the bare minimum to run hybracter
-# and requires to run hybracter install before use
-FROM condaforge/miniforge3:24.11.3-2 AS minimal
+######################################################
+# Minimal contains the bare minimum to run hybracter #
+# and requires to run hybracter install before use   #
+######################################################
+FROM ubuntu:25.04 AS minimal
 
-ENV DEBIAN_FRONTEND=noninteractive
 ENV TERM=xterm-256color
 
-RUN mamba install -y \
+# Install miniforge and hybracter
+ARG MINIFORGE_VERSION=25.3.0-1
+ARG MINIFORGE_PATH=/opt/miniforge
+ENV PATH=${MINIFORGE_PATH}/bin:${PATH}
+RUN set -eux; \
+    apt-get update \
+    && apt-get -y install --no-install-recommends \
+        wget=1.24.5-2ubuntu1 \
+        ca-certificates=20241223 \
+    # Installing miniforge
+    # partly based on https://github.com/conda-forge/miniforge-images/blob/8c784163a44af85c5918ac4bede66d3de2074d82/ubuntu/Dockerfilee
+    && wget -q -O /tmp/miniforge.sh https://github.com/conda-forge/miniforge/releases/download/${MINIFORGE_VERSION}/Miniforge3-${MINIFORGE_VERSION}-Linux-x86_64.sh \
+    && bash /tmp/miniforge.sh -b -p ${MINIFORGE_PATH}/ \
+    # Installing hybracter
+    && mamba install -y \
         bioconda::hybracter==0.11.2 \
-    mamba clean -afy
+    # Cleanup
+    && rm -rf /tmp/miniforge.sh \
+    && find ${MINIFORGE_PATH} -follow -type f -name '*.a' -delete \
+    && find ${MINIFORGE_PATH} -follow -type f -name '*.pyc' -delete \
+    && mamba clean -afy \
+    && apt-get -y --purge autoremove \
+        wget \
+        ca-certificates \
+    && apt-get clean \
+    && rm -rf /var/lib/apt/lists/*
 
-
-# Full is built on top of minimal and contains
-# all databases and dependencies
+################################################
+# Full is built on top of minimal and contains #
+# all databases and dependencies               #
+################################################
 FROM minimal AS full
 RUN hybracter install --medaka \
     && hybracter test-hybrid --use-conda --conda-create-envs-only \
